name: Push

on:
  push:
    tags:
      - '*.*.*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  push:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Pack
        run: dotnet pack -c Release -o ./artifacts

      - name: NuGet push
        run: dotnet nuget push ./artifacts/Lemworks.Generators.Configuration.${{ github.ref_name }}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_LEMWORKS_UPLOAD_API_KEY }}
